#! /bin/bash
# Usage: mongo-dump DESTINATION SOURCE [<options>]
# where DESTINATION is a mongo URI
# and SOURCE is a directory to use for the restore
# and options are any additional options to mongo restore

if [ $# -lt 2 ]; then
  echo "Usage: $(basename $0) DESTINATION SOURCE [options]" >&2
  echo "    DESTINATION:  a Mongo URI" >&2
  echo "    SOURCE:       the restore source directory" >&2
  echo "    options:      see mongoctl restore for options" >&2
  exit 1
fi

DESTINATION="${1}"
SOURCE="${2}"
shift 2
OPTIONS=${@}

# Make sure all relative data is removed.
if [ -d "$SOURCE" ]
then
  SOURCE=$(cd "$SOURCE"; pwd)
  SOURCEPATH=$(dirname "$SOURCE")
  SOURCEDIR=$(basename "$SOURCE")
else
  SOURCEPATH=$(dirname "$SOURCE")
  SOURCEDIR=$(basename "$SOURCE")
  SOURCEPATH=$(cd "$SOURCEPATH"; pwd)
fi

docker run --interactive --tty --rm \
  --volume "${HOME}/.mongoctl:/home/mongoctl/.mongoctl" \
  --volume "${SOURCEPATH}:/dumps" \
  unitive/mongoctl \
  restore ${OPTIONS} "${DESTINATION}" "/dumps/${SOURCEDIR}"
